export const siteConfig = {
  name: "Channim EY",
  title: "Full Stack Developer",
  description: "I build accessible, pixel-perfect, and performant web experiences.",
  email: "channimey1@gmail.com",
  url: "https://example.com",
  github: "https://github.com",
  linkedin: "https://linkedin.com",
  twitter: "https://twitter.com",
  location: "Phnom Penh, Cambodia",
  resume: "https://example.com/resume.pdf",
  certifications: ["Certified Ethical Hacker", "ISC2", "CISSP"],
  stats: {
    yearsExperience: "5+",
    projectsCompleted: "50+",
    vulnerabilitiesFound: "100+",
    companiesSecured: "20+",
    bountiesEarned: "15+",
  },
  navigation: [
    { name: "About", href: "#about" },
    { name: "Experience", href: "#experience" },
    { name: "Projects", href: "#projects" },
    { name: "Skills", href: "#skills" },
    { name: "Contact", href: "#contact" },
  ],
  about: {
    title: "About Me",
    description: "A passionate developer",
  },
  experience: [
    {
      title: "Senior Developer",
      company: "Company",
      role: "Developer",
      period: "2023 - Present",
      date: "2023 - Present",
      description: "Worked on amazing projects",
      technologies: ["React", "Next.js", "Tailwind CSS", "TypeScript"],
    },
    {
      title: "Senior Developer",
      company: "Company",
      role: "Developer",
      period: "2023 - Present",
      date: "2023 - Present",
      description: "Worked on amazing projects",
      technologies: ["React", "Next.js", "Tailwind CSS", "TypeScript"],
    },
    {
      title: "Senior Developer",
      company: "Company",
      role: "Developer",
      period: "2023 - Present",
      date: "2023 - Present",
      description: "Worked on amazing projects",
      technologies: ["React", "Next.js", "Tailwind CSS", "TypeScript"],
    },
  ],
  projects: [
    {
      title: "Project 1",
      description: "A project description",
      href: "https://github.com",
      featured: true,
      github: "https://github.com",
      demo: "https://demo.com",
      technologies: ["React", "Next.js", "TypeScript"],
    },
    {
      title: "Project 1",
      description: "A project description",
      href: "https://github.com",
      featured: true,
      github: "https://github.com",
      demo: "https://demo.com",
      technologies: ["React", "Next.js", "TypeScript"],
    },
    {
      title: "Project 1",
      description: "A project description",
      href: "https://github.com",
      featured: true,
      github: "https://github.com",
      demo: "https://demo.com",
      technologies: ["React", "Next.js", "TypeScript"],
    },
  ],
  skills: {
    security: ["Penetration Testing", "Vulnerability Assessment", "Security Auditing", "OWASP", "Burp Suite"],
    development: ["React", "Next.js", "TypeScript", "Node.js", "Python"],
    tools: ["Git", "Docker", "AWS", "Linux", "VS Code"],
  },
}
