export const siteConfig = {
  name: "EY Channim",
  title: "Software Development & Web/API Security Student",
  description: "I build real university projects while studying software development at IT Academy STEP and web/API penetration testing at ISTAD.",
  email: "channimey1@gmail.com",
  profileImage: "/profile.JPG",
  url: "https://channimey.vercel.app",
  github: "https://github.com/ChannimEY",
  linkedin: "https://www.linkedin.com/in/ey-channim-aa71703b3/",
  facebook: "https://www.facebook.com/ey.channim",
  location: "Phnom Penh, Cambodia",
  resume: "/CV_EY_CHANNIM.pdf",
  certifications: [
    "Software Development - IT Academy STEP",
    "Web/API Penetration Testing - ISTAD",
    "Hack The Box Practice",
    "TryHackMe Practice",
    "PortSwigger Web Security Academy",
    "OverTheWire Wargames",
  ],
  stats: {
    yearsExperience: "Student",
    projectsCompleted: "University",
    vulnerabilitiesFound: "Labs",
    companiesSecured: "STEP",
    bountiesEarned: "ISTAD",
  },
  navigation: [
    { name: "About", href: "#about" },
    { name: "Learning", href: "#experience" },
    { name: "Projects", href: "#projects" },
    { name: "Skills", href: "#skills" },
    { name: "Contact", href: "#contact" },
  ],
  about: {
    title: "About Me",
    description: "A passionate developer",
  },
  experience: [
    {
      title: "Software Development Student",
      company: "IT Academy STEP",
      role: "Software Development Student",
      period: "Current",
      date: "Current",
      description: "Building real academic projects and practicing application development from frontend interfaces to backend services, databases, and mobile apps.",
      technologies: ["HTML", "CSS", "JavaScript", "React", "Next.js", "C++", "Java", "C#", ".NET"],
    },
    {
      title: "Cybersecurity Student",
      company: "ISTAD",
      role: "Web/API Penetration Testing Student",
      period: "Current",
      date: "Current",
      description: "Specializing in web and API security, with practice in reconnaissance, vulnerability testing, authentication issues, authorization logic, and OWASP-style labs.",
      technologies: ["Burp Suite", "Nmap", "Subfinder", "WebGoat", "PortSwigger", "OWASP"],
    },
    {
      title: "Security Lab Practice",
      company: "Hands-on Platforms",
      role: "Cybersecurity Lab Learner",
      period: "Ongoing",
      date: "Ongoing",
      description: "Practicing ethical hacking skills through guided labs, capture-the-flag exercises, and vulnerable applications to improve real testing methodology.",
      technologies: ["Hack The Box", "TryHackMe", "CyLab Security Academy", "OverTheWire", "Linux"],
    },
  ],
  projects: [
    {
      title: "University Web Application",
      description: "A full-stack academic project focused on clean UI, reliable features, and secure application behavior.",
      href: "https://github.com",
      featured: true,
      github: "https://github.com",
      demo: "https://demo.com",
      technologies: ["React", "Next.js", "TypeScript", "Tailwind CSS"],
    },
    {
      title: "Backend API Project",
      description: "A university API project built to practice routing, database design, validation, authentication, and maintainable service structure.",
      href: "https://github.com",
      featured: true,
      github: "https://github.com",
      demo: "https://demo.com",
      technologies: ["Java", "Spring Boot", "SQL", "PostgreSQL"],
    },
    {
      title: "Security Practice Notes",
      description: "A growing collection of web/API security lab practice, testing notes, and lessons from intentionally vulnerable environments.",
      href: "https://github.com",
      featured: true,
      github: "https://github.com",
      demo: "https://demo.com",
      technologies: ["Burp Suite", "Nmap", "WebGoat", "PortSwigger"],
    },
  ],
  skills: {
    security: ["Web/API Pentesting", "OWASP", "Burp Suite", "Nmap", "Subfinder", "WebGoat", "Hack The Box", "TryHackMe", "PortSwigger", "OverTheWire"],
    development: ["HTML", "CSS", "Bootstrap", "Tailwind CSS", "JavaScript", "React.js", "Next.js", "TypeScript", "C++", "Java", "Spring Boot", "C#", ".NET", "Python", "Django", "React Native"],
    tools: ["Figma", "UX/UI Design", "SQL", "MySQL", "PostgreSQL", "Git", "Linux", "VS Code","Postman", "Docker"],
  },
}
